---
- hosts: jalandhar
  gather_facts: no 
  tasks: 
#  - name: Java jar files
#    copy:
#      src: "{{ item }}"
#      dest: /usr/lib/jvm/jdk1.7.0_79/jre/lib/security/
#      owner: root
#      mode: 777
#    with_fileglob:
#      - /root/ansible/files/local_policy.jar
#      - /root/ansible/files/US_export_policy.jar
#
#  - name: Arial Font Jar
#    copy:
#      src: /root/ansible/files/jasperreports-fonts-liberation-2.1.2.jar
#      dest: /opt/glassfish3/glassfish/lib/
#
#  - name: "redirect 8080 to 8080/cbs-jsp"
#    copy:
#      src: /root/ansible/files/index.html
#      dest: /opt/glassfish3/glassfish/domains/domain1/docroot/
#      mode: 777
#   - name: "copy error page"
#     copy:
#            src: files/error.html
#            dest: /opt/glassfish3/glassfish/domains/domain1/applications/
#            mode: 777
#   - name: "mv old log4j to srv"
#     copy:
#            src: /opt/glassfish3/glassfish/lib/log4j-1.2.14.jar
#            dest: /srv
#            remote_src: yes
#            mode: 777
#
#
#   - name: download domain.xml
#     fetch:
#       src: /opt/glassfish3/glassfish/domains/domain1/config/domain.xml
#       dest: ~/ansible/files/domain/{{ inventory_hostname }}-domain.xml
#       flat: yes
  - name: log4j jar files
    copy:
      src: "{{ item }}"
      dest: /opt/glassfish3/glassfish/lib/
      owner: root
      mode: 777
    with_fileglob:
      - /root/ansible/files/log4j_jar/log4j-api-2.12.2.jar
      - /root/ansible/files/log4j_jar/log4j-core-2.12.2.jar
      - /root/ansible/files/log4j_jar/log4j-slf4j-impl-2.12.2.jar
      #- /root/ansible/files/log4j_jar/slf4j-log4j12-1.6.0.jar
...
