- name: Restart Glassfish
  hosts: 
       - jamsedpur
  gather_facts: no
  serial: 5
  tasks: 

          - name: kill java
            shell: pkill -9 java 

          - name: start glassfish
            service:
                 name: glassfish
                 state: started         
