- hosts: all
  tasks:
  - name: Update zabbix server information
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'Server=192.168.1.220'
    - 'ServerActive=192.168.1.220'
    - 'HostMetadata=cbs'

  - name: Add hostname for zabbix-agent
    shell: echo "hostname=`hostname`" >> /etc/zabbix/zabbix_agentd.conf
