---
- hosts:
      - utti
      - morena
      - ujjain
      - mnagar
      - bally
      - ccbl
      - etawah
      - sonbhadra
      - bhind
      - hisar
      - janata
      - ccbl
  become: yes
  user: root
  serial: 5
  gather_facts: no 
  tasks: 
     - name: Copy Java Setup
       copy:
         src: ~/ansible/files/java
         dest: /srv
   
     - name: run java script
       shell: sh /srv/java/javascript.sh


     - name: Correct java version 1.8.0_151 selected
       alternatives:
         name: java
         path: /usr/lib/jvm/jdk1.8.0_151/bin/java

     - name: add parameter for java 8
       lineinfile:
         path: /opt/glassfish3/glassfish/config/osgi.properties
         line: 'jre-1.8=${jre-1.7}'

     - name: Java jar files
       copy:
         src: "{{ item }}"
         dest: /usr/lib/jvm/jdk1.8.0_151/jre/lib/security/
       with_items:
         - /root/ansible/files/java8jar/US_export_policy.jar
         - /root/ansible/files/java8jar/local_policy.jar
    
     - name: kill java
       shell: pkill -9 java 

     - name: start glassfish
       service:
            name: glassfish
            state: started
...
