#!/bin/bash  
# description: Glassfish Start Stop Restart 
# processname: glassfish 
# chkconfig: 244 20 80 
GLASSFISH_HOME=/opt/glassfish3/glassfish
case $1 in 
start) 
sh $GLASSFISH_HOME/bin/asadmin start-domain domain1 
;;  
stop)  
sh $GLASSFISH_HOME/bin/asadmin stop-domain domain1  
;;  
restart) 
sh $GLASSFISH_HOME/bin/asadmin stop-domain domain1  
sh $GLASSFISH_HOME/bin/asadmin start-domain domain1
;;  
esac 
exit 0 
